import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/requireAuth'
import { createAdminSupabaseClient } from '@/lib/supabase-server'
import { resolveTemplate, ALL_TEMPLATES } from '@/lib/templates'

export const dynamic = 'force-dynamic'

/**
 * GET /api/templates?docType=lesson_plan&className=Grade%2010A
 *
 * Returns the resolved Sychar document template definition for the caller's
 * school, plus branding (crest logoUrl + "Generated by Sychar" footer) so Lovable
 * can render the form and the PDF export carries school branding.
 *
 * docType: lesson_plan | record_of_work | tod_report | gc_case_file | nurse_record
 * Omit docType to list all template summaries.
 */
export async function GET(req: NextRequest) {
  const auth = await requireAuth()
  if (auth.unauthorized) return auth.unauthorized

  const url = new URL(req.url)
  const docType = url.searchParams.get('docType')
  const className = url.searchParams.get('className') ?? undefined
  const curriculumParam = url.searchParams.get('curriculum') as 'CBC' | '844' | null

  const svc = createAdminSupabaseClient()

  // Branding + gender profile from the school config.
  const [{ data: tc }, { data: meta }] = await Promise.all([
    svc.from('tenant_configs').select('logo_url, gender_profile').eq('school_id', auth.schoolId).maybeSingle(),
    svc.from('school_metadata').select('name, theme, gender_profile').eq('school_id', auth.schoolId).maybeSingle(),
  ])
  const logoUrl = (tc as any)?.logo_url ?? (meta as any)?.theme?.logo_url ?? null
  const genderProfile = ((tc as any)?.gender_profile ?? (meta as any)?.gender_profile ?? 'mixed') as 'mixed' | 'boys' | 'girls'
  const branding = { schoolName: (meta as any)?.name ?? null, logoUrl, footer: 'Generated by Sychar' }

  if (!docType) {
    return NextResponse.json({
      templates: ALL_TEMPLATES.map((t) => ({ id: t.id, docType: t.docType, name: t.name, curriculum: t.curriculum, genderProfile: t.genderProfile })),
      branding,
    })
  }

  const template = resolveTemplate(docType, {
    className,
    curriculum: curriculumParam ?? undefined,
    genderProfile,
  })

  if (!template) {
    return NextResponse.json({ error: `Unknown docType "${docType}"` }, { status: 400 })
  }

  return NextResponse.json({ template, branding })
}
