// Machine-readable document-template definitions.
//
// These are the single source of truth for the synthesized Sychar templates
// (lesson plan, record of work, teacher-on-duty, counselling, nurse). Lovable
// renders the forms from these definitions; the backend stores filled instances
// and the generate-pdf edge function exports them with school branding + the
// "Generated by Sychar" footer.

export type FieldType =
  | 'text' | 'textarea' | 'number' | 'percent' | 'date' | 'time'
  | 'select' | 'multiselect' | 'chips' | 'checkbox' | 'table' | 'signature'

export interface TemplateField {
  key: string
  label: string
  type: FieldType
  required?: boolean
  options?: string[]          // select / multiselect / chips
  columns?: string[]          // table column headers
  placeholder?: string
  help?: string
  /** This field can be drafted by the AI fill-assistant (/api/ai/template-assist). */
  aiAssist?: boolean
}

export interface TemplateSection {
  id: string
  title: string
  description?: string
  fields: TemplateField[]
}

export type Curriculum = 'CBC' | '844' | 'both'

export interface Template {
  id: string
  /** Which dashboard document this is: lesson_plan | record_of_work | tod_report | gc_case_file | nurse_record */
  docType: string
  name: string
  curriculum?: Curriculum
  /** Optional gender variant for counselling: 'mixed' | 'boys' | 'girls' */
  genderProfile?: 'mixed' | 'boys' | 'girls'
  branding: { footer: string; logoFrom: string }
  sections: TemplateSection[]
}

export const SYCHAR_BRANDING = {
  footer: 'Generated by Sychar',
  logoFrom: 'tenant_configs.logo_url',
} as const

/** Curriculum auto-detection from a class/level name (Grade N → CBC, Form N → 8-4-4). */
export function curriculumForClass(className: string): Exclude<Curriculum, 'both'> {
  return /grade\s*\d+/i.test(className) ? 'CBC' : '844'
}
