// Synthesized Minutes-of-Meeting template (ALL schools, branded). The school name
// and department/committee are auto-filled by the system from tenant_configs +
// the meeting record; the crest is pulled from tenant_configs.logo_url and the
// footer is "Generated by Sychar". Filled instances live in `meetings`
// (summary / decisions / attendees / minuted_at). PDF doc-type: meeting_minutes.

import { Template, SYCHAR_BRANDING } from './types'

export const MEETING_MINUTES: Template = {
  id: 'meeting_minutes_v1',
  docType: 'meeting_minutes',
  name: 'Minutes of Meeting',
  branding: SYCHAR_BRANDING,
  sections: [
    {
      id: 'header', title: 'Meeting Details',
      description: 'School name and department are auto-filled by the system.',
      fields: [
        { key: 'school_name', label: 'School', type: 'text', required: true, help: 'Auto-filled from the tenant.' },
        { key: 'meeting_type', label: 'Meeting Type', type: 'select', required: true, options: ['BOM', 'Staff', 'Department', 'PTA', 'Academic', 'Committee', 'Other'] },
        { key: 'department', label: 'Department / Committee', type: 'text', help: 'Auto-filled for department meetings.' },
        { key: 'title', label: 'Meeting Title / Subject', type: 'text', required: true },
        { key: 'venue', label: 'Venue', type: 'text' },
        { key: 'meeting_date', label: 'Date', type: 'date', required: true },
        { key: 'start_time', label: 'Start Time', type: 'time' },
        { key: 'end_time', label: 'End Time', type: 'time' },
        { key: 'convener', label: 'Convener / Chairperson', type: 'text', required: true },
        { key: 'minute_taker', label: 'Minute Taker / Secretary', type: 'text', required: true },
      ],
    },
    {
      id: 'attendance', title: 'Attendance',
      fields: [
        { key: 'attendees', label: 'Members Present', type: 'table', columns: ['Name', 'Designation', 'Signature'] },
        { key: 'apologies', label: 'Apologies', type: 'textarea' },
        { key: 'absent', label: 'Absent', type: 'textarea' },
      ],
    },
    {
      id: 'agenda', title: 'Agenda',
      fields: [
        { key: 'agenda_items', label: 'Agenda Items', type: 'table', columns: ['No.', 'Agenda Item'] },
        { key: 'prev_minutes_confirmed', label: 'Minutes of previous meeting confirmed', type: 'checkbox' },
        { key: 'matters_arising', label: 'Matters Arising', type: 'textarea', aiAssist: true },
      ],
    },
    {
      id: 'deliberations', title: 'Deliberations',
      fields: [
        { key: 'summary', label: 'Discussion / Minutes', type: 'textarea', required: true, aiAssist: true },
        { key: 'decisions', label: 'Resolutions / Decisions', type: 'table', columns: ['No.', 'Resolution'] },
      ],
    },
    {
      id: 'actions', title: 'Action Points',
      fields: [
        { key: 'action_points', label: 'Action Points', type: 'table', columns: ['Action', 'Responsible', 'Deadline'] },
        { key: 'next_meeting', label: 'Date of Next Meeting', type: 'date' },
        { key: 'aob', label: 'Any Other Business (A.O.B)', type: 'textarea' },
      ],
    },
    {
      id: 'signoff', title: 'Confirmation',
      fields: [
        { key: 'chair_signature', label: 'Chairperson Signature', type: 'signature' },
        { key: 'secretary_signature', label: 'Secretary Signature', type: 'signature' },
        { key: 'minuted_at', label: 'Minutes Recorded On', type: 'date' },
      ],
    },
  ],
}
