-- ── teacher_documents ─────────────────────────────────────────────────────────
-- Schemes of work, lesson plans, records of work uploaded or AI-generated by teachers.
CREATE TABLE IF NOT EXISTS teacher_documents (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id    uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  staff_id     uuid NOT NULL REFERENCES staff_records(id) ON DELETE CASCADE,
  category     text NOT NULL CHECK (category IN ('scheme_of_work','lesson_plan','record_of_work')),
  title        text NOT NULL,
  description  text,
  subject      text,
  class_label  text,
  term         text,
  source       text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','ai','ocr')),
  storage_path text,
  ai_summary   text,
  status       text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved')),
  created_at   timestamptz DEFAULT now()
);

ALTER TABLE teacher_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "teacher_docs_school_isolation" ON teacher_documents
  USING (school_id = get_my_school_id());

CREATE INDEX IF NOT EXISTS idx_teacher_docs_staff   ON teacher_documents (school_id, staff_id, category);
CREATE INDEX IF NOT EXISTS idx_teacher_docs_status  ON teacher_documents (school_id, status);

-- ── counselor_self_referrals ──────────────────────────────────────────────────
-- Students or staff who self-refer to the G&C counselor.
CREATE TABLE IF NOT EXISTS counselor_self_referrals (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id    uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  student_id   uuid REFERENCES students(id) ON DELETE SET NULL,
  student_name text NOT NULL,
  urgency      text NOT NULL DEFAULT 'medium' CHECK (urgency IN ('low','medium','high')),
  topic        text NOT NULL,
  note         text,
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','reviewed','closed')),
  created_at   timestamptz DEFAULT now()
);

ALTER TABLE counselor_self_referrals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "self_referrals_school_isolation" ON counselor_self_referrals
  USING (school_id = get_my_school_id());

CREATE INDEX IF NOT EXISTS idx_self_referrals_school ON counselor_self_referrals (school_id, status);
